<!DOCTYPE html>
<?php
use Phpolar\Phpolar\Tests\Fakes\TestForm;

/**
 * @var TestForm $view
 */
$view = $this;
?>
<html>
    <body>
        <h1><?= $view->title ?></h1>
        <form action="/save">
            <label for="myInput"><?= $view->getLabel('myInput') ?></label>
            <input id="myInput"
                type="<?= $view->getInputType("myInput")->asString() ?>"
                name="myInput"
                value="<?= $view->myInput ?>" />
            <span><?= $view->getFieldErrorMessage("myInput") ?></span>
            <input type="submit" value="Submit" />
        </form>
    </body>
</html>