<!DOCTYPE html>
<?php
use Phpolar\Phpolar\Tests\Fakes\ModelList;

/**
 * @var ModelList $view
 */
$view = $this;
?>
<html>
    <head>
      <style>
        .success {
            color: black;
            background-color: lime;
            display: inline-block;
            width: 300px;
            height: 150px;
        }
      </style>
    </head>
    <body>
        <h1><?= $view->title ?></h1>
        <ul>
<?php foreach ($view->list() as $item): ?>
            <li><?= $item->myInput ?></li>
<?php endforeach ?>
        </ul>
        <aside class="success"><?= $view->successMsg ?></aside>
    </body>
</html>
